Faithful Hoops Training/Models/Address.cs
using System.ComponentModel.DataAnnotations;

namespace FaithfulHoopsTraining.Models
{
    public class Address
    {
        [Key]
        public int Id { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
    }
}

Faithful Hoops Training/Models/AppUser.cs
using System.ComponentModel.DataAnnotations;

namespace FaithfulHoopsTraining.Models
{
    public class AppUser
    {
        [Key]
        public string Id { get; set; }
        public int? PlayersAge { get; set; }
        public string? PlayersName { get; set; }
        public Address? Address { get; set; }
        public ICollection<TrainSession> TrainSessions { get; set; }
        public ICollection<HoopSession> HoopSessions { get; set; }
    }
}

Faithful Hoops Training/Models/ErrorViewModel.cs
namespace FaithfulHoopsTraining.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Faithful Hoops Training/Models/HoopSession.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using FaithfulHoopsTraining.Data.Enum;

namespace FaithfulHoopsTraining.Models
{
    public class HoopSession
    {
        [Key]
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        [ForeignKey("Address")]
        public int AddressId { get; set; }
        public Address Address { get; set; }
        public HoopSessionCategory HoopSessionCategory { get; set; }
        [ForeignKey("AppUser")]
        public string? AppUserId { get; set; }
        public AppUser? AppUser { get; set; }
    }
}

Faithful Hoops Training/Models/Hoops.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using FaithfulHoopsTraining.Data.Enum;

namespace FaithfulHoopsTraining.Models
{
    public class Hoops
    {
        [Key]
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        [ForeignKey("Address")]
        public int AddressId { get; set; }
        public Address Address { get; set; }
        public HoopsCategory HoopsCategory { get; set; }
        [ForeignKey("AppUser")]
        public string? AppUserId { get; set; }
        public AppUser? AppUser { get; set; }
    }
}

Faithful Hoops Training/Models/TrainSession.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using FaithfulHoopsTraining.Data.Enum;

namespace FaithfulHoopsTraining.Models
{
    public class TrainSession
    {
            [Key]
            public int Id { get; set; }
            public string? Title { get; set; }
            public string? Description { get; set; }
            public string? Image { get; set; }
            [ForeignKey("Address")]
            public int? AddressId { get; set; }
            public Address? Address { get; set; }
            public TrainSessionCategory TrainSessionCategory { get; set; }
            [ForeignKey("AppUser")]
            public string? AppUserId { get; set; }
            public AppUser? AppUser { get; set; }
    }
}

Faithful Hoops Training/Models/Training.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using FaithfulHoopsTraining.Data.Enum;

namespace FaithfulHoopsTraining.Models
{
    public class Training
    {
            [Key]
            public int Id { get; set; }
            public string? Title { get; set; }
            public string? Description { get; set; }
            public string? Image { get; set; }
            [ForeignKey("Address")]
            public int? AddressId { get; set; }
            public Address? Address { get; set; }
            public TrainingCategory TrainingCategory { get; set; }
            [ForeignKey("AppUser")]
            public string? AppUserId { get; set; }
            public AppUser? AppUser { get; set; }
    }
}

Faithful Hoops Training/Controllers/HomeController.cs
using FaithfulHoopsTraining.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FaithfulHoopsTraining.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Faithful Hoops Training/Controllers/HoopSessionController.cs
using FaithfulHoopsTraining.Data;
using FaithfulHoopsTraining.Interfaces;
using FaithfulHoopsTraining.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FaithfulHoopsTraining.Controllers
{
    public class HoopSessionController : Controller
    {
        private readonly IHoopSessionRepository _hoopSessionRepository;

        public HoopSessionController(IHoopSessionRepository hoopSessionRepository)
        {
            _hoopSessionRepository = hoopSessionRepository;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<HoopSession> hoopSessions = await _hoopSessionRepository.GetAll();
            return View(hoopSessions);
        }
        public async Task<IActionResult> HoopDetail(int id) 
        { 
            HoopSession hoopSession = await _hoopSessionRepository.GetByIdAsync(id);
            return View(hoopSession);
        }
        public IActionResult HoopCreate() 
        {
         return View();
        }

        [HttpPost]
        public async Task<IActionResult> HoopCreate(HoopSession hoopSession)
        {
            if (!ModelState.IsValid) 
            {
                return View(hoopSession);
            }

            _hoopSessionRepository.Add(hoopSession);
            return RedirectToAction("Index");
        }
    }
}

Faithful Hoops Training/Controllers/TrainSessionController.cs
using FaithfulHoopsTraining.Data;
using FaithfulHoopsTraining.Interfaces;
using FaithfulHoopsTraining.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FaithfulHoopsTraining.Controllers
{
    public class TrainSessionController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ITrainSessionRepository _trainSessionRepository;

        public TrainSessionController(ITrainSessionRepository trainSessionRepository)
        {
            _trainSessionRepository = trainSessionRepository;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<TrainSession> trainSessions = await _trainSessionRepository.GetAll();
            return View(trainSessions);
        }
        public async Task<IActionResult> TrainDetail(int id)
        {
            TrainSession trainSession = await _trainSessionRepository.GetByIdAsync(id);
            return View(trainSession);
        }
    }
}

Faithful Hoops Training/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
        <symbol id="bootstrap" viewBox="0 0 118 94">
            <title>Bootstrap</title>
            <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>
        </symbol>
        <symbol id="arrow-right-short" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z" />
        </symbol>
        <symbol id="check2-circle" viewBox="0 0 16 16">
            <path d="M2.5 8a5.5 5.5 0 0 1 8.25-4.764.5.5 0 0 0 .5-.866A6.5 6.5 0 1 0 14.5 8a.5.5 0 0 0-1 0 5.5 5.5 0 1 1-11 0z" />
            <path d="M15.354 3.354a.5.5 0 0 0-.708-.708L8 9.293 5.354 6.646a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0l7-7z" />
        </symbol>
    </svg>

    <div class="container my-5">
        <div class="p-5 text-center bg-body-tertiary rounded-3">
            <svg class="bi mt-4 mb-3" style="color: var(--bs-indigo);" width="100" height="100"><use xlink:href="#bootstrap" /></svg>
            <h1 class="text-body-emphasis">Welcome to FHT by Kristofer Norman</h1>
            <p class="col-lg-8 mx-auto fs-5 text-muted">
            <p>An online platform dedicated to basketball enthusiasts who want to take their game to the next level while glorifying God. This platform will allow you to schedule the best time for your workouts, schedule basketball training, and meet other athletes in your area.
            </p>
            <div class="d-inline-flex gap-2 mb-5">
                <button class="d-inline-flex align-items-center btn btn-primary btn-lg px-4 rounded-pill" type="button">
                    Call to action
                    <svg class="bi ms-2" width="24" height="24"><use xlink:href="#arrow-right-short" /></svg>
                </button>
                <button class="btn btn-outline-secondary btn-lg px-4 rounded-pill" type="button">
                    Secondary link
                </button>
            </div>
        </div>
    </div>

<div class="album py-5 bg-body-tertiary">
    <div class="container">
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    <div class="col">
        <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c" /><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
            <div class="card-body">
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                        <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                    <small class="text-body-secondary">9 mins</small>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c" /><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
            <div class="card-body">
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                        <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                    <small class="text-body-secondary">9 mins</small>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c" /><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
            <div class="card-body">
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                        <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                    <small class="text-body-secondary">9 mins</small>
                </div>
            </div>
        </div>
       </div>
      </div>
     </div>
   </div>

Faithful Hoops Training/Views/HoopSession/HoopCreate.cshtml
@using FaithfulHoopsTraining.Data.Enum
@model HoopSession
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form method="post" asp-action="Create">
    <div class="mb-3">
        <label asp-for = "Title"> Title</label>
        <input asp-for ="Title" class="form-control">
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Description"> Description</label>
        <input asp-for="Description" class="form-control">
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Image"> Image</label>
        <input asp-for="Image" class="form-control">
        <span asp-validation-for="Image" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="HoopSessionCategory"> HoopSessionCategory</label>
        <select asp-for="HoopSessionCategory" asp-items="@Html.GetEnumSelectList<HoopSessionCategory>()">
                 <option>--Select--</option>
        </select>
        <span asp-validation-for="HoopSessionCategory" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Address.Street"> Street</label>
        <input asp-for="Address.Street" class="form-control">
        <span asp-validation-for="Address.Street" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Address.City"> City</label>
        <input asp-for="Address.City" class="form-control">
        <span asp-validation-for="Address.City" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Address.State"> State</label>
        <input asp-for="Address.State" class="form-control">
        <span asp-validation-for="Address.State" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Faithful Hoops Training/Views/HoopSession/HoopDetail.cshtml
@model HoopSession
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!-- Page Content -->
<div class="container">

    <!-- Portfolio Item Heading -->
    <h1 class="my-4">
        Page Heading
        <small>Secondary Text</small>
    </h1>

    <!-- Portfolio Item Row -->
    <div class="row">

        <div class="col-md-8">
            <img class="img-fluid" src="@Model.Image" alt="">
        </div>

        <div class="col-md-4">
            <h3 class="my-3">@Model.Title</h3>
            <p>@Model.Description</p>
            <h3 class="my-3">Location</h3>
            <ul>
                <li>@Model.Address.City, @Model.Address.State</li>
                <li> (Game type) @Model.HoopSessionCategory</li>
            </ul>
        </div>

    </div>
    <!-- /.row -->
    <!-- Related Projects Row -->
    <h3 class="my-4">Related Projects</h3>

    <div class="row">

        <div class="col-md-3 col-sm-6 mb-4">
            <a href="#">
                <img class="img-fluid" src="https://via.placeholder.com/500x300" alt="">
            </a>
        </div>

        <div class="col-md-3 col-sm-6 mb-4">
            <a href="#">
                <img class="img-fluid" src="https://via.placeholder.com/500x300" alt="">
            </a>
        </div>

        <div class="col-md-3 col-sm-6 mb-4">
            <a href="#">
                <img class="img-fluid" src="https://via.placeholder.com/500x300" alt="">
            </a>
        </div>

        <div class="col-md-3 col-sm-6 mb-4">
            <a href="#">
                <img class="img-fluid" src="https://via.placeholder.com/500x300" alt="">
            </a>
        </div>

    </div>
    <!-- /.row -->

</div>
<!-- /.container -->

Faithful Hoops Training/Views/HoopSession/Index.cshtml
@model IEnumerable<HoopSession>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row"> 
            @foreach (var item in Model)
            {
                <div class="col-md-4">
                    <div class="card shadow-sm">
                        <img class="card-img-top" src="@item.Image"> 
                        <div class="card-body">
                            <p class="card-text">@item.Title</p>
                            <p class="card-text">@item.Description</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a asp-controller="hoopSession" asp-action="HoopDetail" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">View</a>
                                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                                </div>
                                <small class="text-body-secondary">@item.HoopSessionCategory</small>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Faithful Hoops Training/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FHT</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Faithful Hoops Training.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Faithful Hoops Training</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HoopSession" asp-action="Index">Hoopage</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TrainSession" asp-action="Index">Training</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Faithful Hoops Training - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Faithful Hoops Training/Views/TrainSession/Index.cshtml
@model IEnumerable<TrainSession>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-4">
                    <div class="card shadow-sm">
                        <img class="card-img-top" src="@item.Image">
                        <div class="card-body">
                            <p class="card-text">@item.Title</p>
                            <p class="card-text">@item.Description</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a asp-controller="trainSession" asp-action="TrainDetail" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">View</a>
                                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                                </div>
                                <small class="text-body-secondary">@item.TrainSessionCategory</small>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Faithful Hoops Training/Views/TrainSession/TrainDetail.cshtml
@model TrainSession
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!-- Page Content -->
<div class="container">

    <!-- Portfolio Item Heading -->
    <h1 class="my-4">
        Page Heading
        <small>Secondary Text</small>
    </h1>

    <!-- Portfolio Item Row -->
    <div class="row">

        <div class="col-md-8">
            <img class="img-fluid" src="@Model.Image" alt="">
        </div>

        <div class="col-md-4">
            <h3 class="my-3">@Model.Title</h3>
            <p>@Model.Description</p>
            <h3 class="my-3">Location</h3>
            <ul>
                <li>@Model.Address.City, @Model.Address.State</li>
                <li> ( Skill Level ) @Model.TrainSessionCategory</li>
            </ul>
        </div>

    </div>
    <!-- /.row -->
    <!-- Related Projects Row -->
    <h3 class="my-4">Related Projects</h3>

    <div class="row">

        <div class="col-md-3 col-sm-6 mb-4">
            <a href="#">
                <img class="img-fluid" src="https://via.placeholder.com/500x300" alt="">
            </a>
        </div>

        <div class="col-md-3 col-sm-6 mb-4">
            <a href="#">
                <img class="img-fluid" src="https://via.placeholder.com/500x300" alt="">
            </a>
        </div>

        <div class="col-md-3 col-sm-6 mb-4">
            <a href="#">
                <img class="img-fluid" src="https://via.placeholder.com/500x300" alt="">
            </a>
        </div>

        <div class="col-md-3 col-sm-6 mb-4">
            <a href="#">
                <img class="img-fluid" src="https://via.placeholder.com/500x300" alt="">
            </a>
        </div>

    </div>
    <!-- /.row -->

</div>
<!-- /.container -->